title: Fundamentos de Engenharia de Tráfego
description: Prof. Diego Camargo - [Lattes](http://lattes.cnpq.br/0138793013112199). Disciplina do Curso de Engenharia de Transportes do Departamento de Engenharia de Transportes do Centro Federal de Educação Tecnológica de Minas Gerais
show_downloads: false
google_analytics:
theme: jekyll-theme-modernist
